# Generated by Django 4.2.7 on 2025-08-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('specialization', models.CharField(choices=[('CARDIOLOGY', 'Cardiology'), ('NEUROLOGY', 'Neurology'), ('ORTHOPEDICS', 'Orthopedics'), ('PEDIATRICS', 'Pediatrics'), ('DERMATOLOGY', 'Dermatology'), ('PSYCHIATRY', 'Psychiatry'), ('GENERAL', 'General Medicine'), ('ONCOLOGY', 'Oncology'), ('RADIOLOGY', 'Radiology'), ('SURGERY', 'Surgery'), ('OTHER', 'Other')], max_length=20)),
                ('experience_years', models.PositiveIntegerField()),
                ('qualification', models.CharField(max_length=200)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
